#!/bin/bash

set -e

if [[ -d "docker-entrypoint.d" ]]
then
echo "Running docker-entrypoint.d files"
/bin/run-parts docker-entrypoint.d
fi

# Start the proxy in the background
echo "Starting proxy server"
python3 /app/proxy.py &

echo "Running $@"

exec "$@"