# fly.toml app configuration file generated for xsslab-challs on 2025-04-07T06:48:25+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flyctf-challs'
primary_region = 'sin'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[[mounts]]
source = 'data'
destination = '/data'

[[services]]
http_checks = []
tcp_checks = []
script_checks = []
protocol = 'tcp'
internal_port = 5000
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0

[[services.ports]]
port = 5000
handlers = ['tls', 'http']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
