version: '3'

services:
  proxy:
    image: nginx:latest
    restart: always
    expose:
      - "80"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    depends_on:
      - bot
      - web
  web:
    build:
      context: src
    environment:
      - PORT=80
    networks:
      - internal
  bot:
    build:
      context: bot
      args:
        - BROWSER=chromium
    restart: always
    environment:
      APPNAME: Admin
      APPURL: http://proxy/
      APPURLREGEX: ^http(|s)://.*$
      APPFLAG: dev{flag}
      APPLIMIT: 2
      APPLIMITTIME: 60
      USE_PROXY: 1
      DISPLAY: ${DISPLAY}
    networks:
      - internal
      # uncoment this if you need to run the bot in GUI mode
      # run this before running the docker container if you're use xauth `sudo xhost +local:docker`
      # volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  internal:
